name: PyPI Linux Wheels

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-wheels:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # (This step is harmless but not used by the manylinux build)
      # You can keep or remove it.
      - name: Install libtiff on host (not used by manylinux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libtiff-dev

      - name: Build wheels (Linux, CPython)
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_OUTPUT_DIR: dist
          # Use a known image; 2014 works well for most projects
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          # Install libtiff *inside* the manylinux image
          CIBW_BEFORE_ALL_LINUX: >
            bash -exc 'if command -v yum; then yum -y install libtiff-devel;
            elif command -v microdnf; then microdnf -y install libtiff-devel;
            elif command -v dnf; then dnf -y install libtiff-devel;
            else echo "No package manager found" >&2; exit 1; fi'

      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
